# Generated by Django 3.0.2 on 2020-01-10 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200, verbose_name='название поста')),
                ('post_text', models.TextField(verbose_name='текст поста')),
                ('pub_date', models.DateTimeField(verbose_name='дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='имя пользователя')),
                ('quantity_post', models.CharField(max_length=20, verbose_name='количество постов')),
                ('register_date', models.DateTimeField(verbose_name='дата регистрации')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='имя пользователя')),
                ('comment_text', models.CharField(max_length=200, verbose_name='название поста')),
                ('comment_date', models.DateTimeField(verbose_name='дата комментирования')),
                ('post_comm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KgBlog.Post')),
            ],
        ),
    ]
