# Generated by Django 3.0.2 on 2020-01-17 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KgBlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_name',
            new_name='author_name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post_comm',
        ),
    ]
